# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1fdaddc27413c31c54d6f42203660c8c611011c7d8e6959cdd59c1d47f038393a12ec1997cea1613db43b20a189e5ca5066f0ac566fbebe2aa1f7cb0e95171d

test:
  secret_key_base: 470b987306c470bdb9e6bd98a0c49cf2e34b7efa2e26ae7386cff8d1ccebbabd5f020f5bb8ce08d5c1ec528302b36e7a7616841fb4306bf10294107fbed581f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
